'use strict';

module.exports = {
  'QUOTA_EXCEEDED_ERR': 'QUOTA_EXCEEDED_ERR',
  'NOT_FOUND_ERR': 'NOT_FOUND_ERR',
  'SECURITY_ERR': 'SECURITY_ERR',
  'INVALID_MODIFICATION_ERR': 'INVALID_MODIFICATION_ERR',
  'INVALID_STATE_ERR': 'INVALID_STATE_ERR',
  'UNKNOWN_ERROR': 'UNKNOWN_ERROR',
  'NO_SUPPORT': 'NO_SUPPORT'
};
